# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c57e6b83afae5f4f79a174fb6b2d89c8eb7b8a758508e24ff828af5d8dafdf9d67f6fe31fd42a342beec54943d492e0c86a0a14d51a18b1b4e4237b6357dc57a

test:
  secret_key_base: 6594f7a0603d38374c0860555a9bfc9fa081effcc51a3980119d0bbd13112973b0d22d23b814634f43dc835cd3b63ea0e431f37e32dcca0b65fc5ab55a39c189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
